### ISSUE TITLE
the zip files in the data folder

### ISSUE THREAD

**Issue by xyl-507** [google-research-datasets/LaGOT#1]
Hello! @2006pmach 
There seems to be a problem with the zip files in the data folder. It can't be extracted. 
In addition, LaSOT only provides the whole sequence and test set, and the validation set in your paper is the test set？
Looking forward to your reply.

**Comment by akuznetsa** [comment]
@xyl-507 I just tested that the files can be extracted; you need to download them first though. If it doesnt work please provide us with the error message you are getting.

Regarding the splits: we provide annotations on the test set of LaSOT, this is correct. Sorry for the confusion in names

**Comment by xyl-507** [comment]
Hello! @akuznetsa 
I re-downloaded the repository and got an error during the unzipping process:
![image](https://github.com/google-research-datasets/LaGOT/assets/69385203/df146e8c-1ac7-40df-90a6-e89bee75a22f)

Also, I checked the size of the file, only 130+ bytes, is this correct?
Thanks！

**Comment by akuznetsa** [comment]
The archive is stored using Git LFS. I think this needs to be installed separately to checkout the data correctly. What you can try to do is to manually download the archive and unzip it. The side of both archives is around 200 Mb

**Comment by xyl-507** [comment]
@akuznetsa 
Thanks for your help, I didn't use git lfs to download. I have solved the problem.
In addition, the TaMOs model you uploaded on pytracking seems to have misplaced links, opening only raw results. https://github.com/visionml/pytracking/blob/master/MODEL_ZOO.md#Models-1

**Comment by akuznetsa** [comment]
Right, thanks for flaggin this! For now you can use those links to download ckpt files:

resnet50: https://drive.google.com/file/d/1oHnVv4hbfGm5CHTaEbPWUkMyRJ6tzt7d/view
swin: https://drive.google.com/file/d/1YFm-z-M02bq5Rag9tuqSqZ7r3H3X0YBw/view

We will update the links in pytracking repository

**Comment by xyl-507** [comment]
Thank you for your outstanding contributions!
